"use strict";
exports.__esModule = true;
var car = "Honda";
var color = undefined;
var Model = 2005;
var speed = true;
var Fast = null;
console.warn("true statements");
console.warn(car === 'Honda');
console.warn(color === undefined);
console.warn(Model === 2005);
console.warn(speed === true);
console.warn(Fast === null);
console.warn("\nfalse statements");
console.warn(car === 'Mazda');
console.warn(car === null);
console.warn(color === "red");
console.warn(Model === 2007);
console.warn(Fast === true);
